- docs/management/health.md
The table under Health Contributors doesn't render.
https://steeltoe.io/docs/7-management/6-%252fhealth
> Fix markdown syntax error in documentation

- docs/configuration/cloud-foundry-provider.md
ConfigureCloudFoundryService<TOption>() contract has changed to use CloudFoundryServicesOptions instead of AbstractServiceOptions, updated code sample to best reflect based on test in https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Configuration/test/CloudFoundryCore.Test/MySqlServiceOption.cs
Addresses #56
> Updated Code samples and documentation

- api-filter.yml
- template/steeltoe/partials/toc.tmpl.partial
- template/steeltoe/styles/main.css
- Remove style bleed from api browser nav into docs nav
- Remove OpenCensus namespace from metadata results
- Consistent namespace linking for default namespace
> API Browser Navigation Enhancements

- template/steeltoe/partials/navbar.tmpl.partial
Add Steeltoe Initializr to "Get Started" nav menu section
- Addresses [Issue: MainSite - Access Steeltoe Initializr](https://github.com/SteeltoeOSS/MainSite/issues/18)
- Complements [PR: MainSite Menu Initializr](https://github.com/SteeltoeOSS/MainSite/pull/64)
> Add Initializr to nav menu

- template/steeltoe/styles/main.css
`Table of Contents` button was running into logo in mobile view
Previous:
New:
> Restore Header Spacing in Mobile View

- api-all.json
- api-filter.yml
- api-v2.json
- Exclude packages causing metadata build issues on Linux/OSX environments
- Set target framework to .NET Core 3.1 for version 2 (2.x branch) metadata being generated
Closes #147
> DocFX Metadata Compatibility with Linux/OSX

- .gitignore
- api/v3/management/cloud-foundry.md
- api/v3/welcome/index.md
- Add links to subpages from the v3 welcome page
- improve actuator CF integration page #121 
- add `_site` back to the .gitignore
> Welcome page links, CF Actuator Integration

- api/v2/tracing/index.md
- guides/cloud-management/distributed-tracing.md
Fix for [MainSite Issue: Missing namespace for extension method in Distributed Tracing getting started](https://github.com/SteeltoeOSS/MainSite/issues/11)
> Distributed Tracing Namespace

- api/v2/circuitbreaker/hystrix.md
- api/v2/configuration/config-server-provider.md
- api/v2/discovery/netflix-eureka.md
- api/v3/circuitbreaker/hystrix.md
- api/v3/configuration/config-server-provider.md
- api/v3/discovery/initialize-discovery-client.md
- api/v3/discovery/netflix-eureka.md
- app.UseDiscoveryClient() is not needed in 3.1.0+
- updated links for SCS 
- added a note about Hystrix dashboard being deprecated
> app.UseDiscoveryClient() deprecated, update SCS links

- api/v3/connectors/redis.md
Since Microsoft Azure Service Broker isn't supported anymore, update link reference to Cloud Service Broker (CSB).
> Reference that Redis connector works with Cloud Service Broker

- .github/workflows/stage-prod-swap.yml
Update the link to mainsite before and after performing a staging slot swap
Also waits 60 seconds (about how long before the app goes offline when updating the docker image) before starting a loop that curls every 5 seconds so we're sure the app is up before kicking it to the prod slot
> Enhance GitHub Actions

- .github/workflows/build-and-stage.yml
- README.md
- api-v4.json
- api/browser/v4/all/index.md
- build-metadata.sh
- main-site.localhost.json
- template/steeltoe/partials/navbar.tmpl.partial
- template/steeltoe/partials/toc.tmpl.partial
Fixes merge errors from #323 and removes components deleted in Steeltoe v4.
> Post-merge fixes

- api/v4/management/health.md
also update sample health json and default value for ShowDetails
> Add Ping Contributor

- .github/workflows/build-and-stage.yml
- .github/workflows/pr-cleanup.yml
- .github/workflows/stage-prod-swap.yml
- separate build and deploy as unique jobs (so we can re-run deployment to staging after a stage/prod swap)
- update action versions
- align styles with other Steeltoe GH Actions
> Workflow updates

- .github/workflows/build-and-stage.yml
- 404.html
- nginx.conf
Adds a 404 page to source and nginx config
> Add a custom not-found page

- docs/docs/v4/management/cloud-foundry.md
- docs/docs/v4/management/health.md
- docs/docs/v4/management/httpexchanges.md
- docs/docs/v4/management/hypermedia.md
Update docs for actuator changes from https://github.com/SteeltoeOSS/Steeltoe/pull/1520.
> Update docs for actuator changes

- .vscode/settings.json
- docs/docs/v4/configuration/cloud-foundry-provider.md
- docs/docs/v4/security/certificate.md
- docs/docs/v4/security/jwt-bearer.md
- docs/docs/v4/security/sso-open-id.md
Documentation for https://github.com/SteeltoeOSS/Steeltoe/pull/1525
Resolves https://github.com/SteeltoeOSS/Steeltoe/issues/1527
> Document reverse proxy changes and cross-platform certificate auth

- docs/docs/v4/welcome/prerequisites.md
Contributes to https://github.com/SteeltoeOSS/Samples/issues/398.
> Update references to new dev feed

- .gitignore
- docs/articles/index.md
- docs/articles/releases/steeltoe-4-0-0-rc1.md
- docs/articles/toc.yml
- src/Steeltoe.io/Components/Pages/Home.razor
- src/Steeltoe.io/appsettings.json
- src/Steeltoe.io/wwwroot/css/site.css
Additional news-related updates:
- add new post and the missing 3.2.2 post, remove 2 oldest
- don't need target=_blank
- add separation to list items
> Add blog post for 4.0@rc1

- docs/docs/v4/discovery/hashicorp-consul.md
Update Consul scheme setting for https://github.com/SteeltoeOSS/Steeltoe/pull/1596
> Change Consul scheme setting to computed
