SteeltoeOSS/Documentation

- docs/management/cloud-foundry.md
- docs/management/env.md
- docs/management/health.md
- docs/management/heapdump.md
- docs/management/hypermedia.md
- docs/management/info.md
- docs/management/loggers.md
- docs/management/mappings.md
- docs/management/metrics.md
- docs/management/prometheus.md
- docs/management/refresh.md
- docs/management/threaddump.md
- docs/management/tracing.md
- docs/management/using-endpoints.md
> Update all UseXXXActuator to use Map<XXXEndpoint>

- docs/management/metric-observers.md
- docs/management/prometheus.md
- docs/management/using-endpoints.md
> Docs fixes

- template/steeltoe/partials/toc.tmpl.partial
- template/steeltoe/styles/main.css
- template/steeltoe/styles/main1.js
- Ability to view table of contents in mobile view
> Mobile Table of Contents

- api/browser/v3/all/index.md
- docfx.json
- template/steeltoe/partials/affix.tmpl.partial
- template/steeltoe/partials/navbar.tmpl.partial
- template/steeltoe/partials/toc.tmpl.partial
- template/steeltoe/styles/main.css
- template/steeltoe/styles/main1.js
- Added Sidebar access in mobile view
- Added landing page (now can be accessed at `/api/browser/v3/all`)
Landing Page
Mobile Sidebar
> Landing Page & Mobile Sidebar 

- articles/index.md
- template/steeltoe/styles/main.css
- Blog list live preview
- Blog list design change
**Live Preview**
> Blog Live Preview and Formatting

- articles/index.md
- template/steeltoe/styles/main.css
- Highlight each blog item on hover
- Entire blog item is clickable (not just blog date link)
- Removed static highlight on first blog item
- Changed "New" to "Latest" blog on first blog item
- Live preview shows on blog item highlight (not just blog date link)
> Blog List UX Changes

- template/steeltoe/layout/_master.tmpl
- template/steeltoe/partials/toc.tmpl.partial
- template/steeltoe/styles/docfx.js
- template/steeltoe/styles/main.css
- Add additional style breakpoints
- Handle table view (toc and sidebar)
- Maximize page width for various browser sizes
Handles MainSite Issues below:
- [Blog page needs some design updates](https://github.com/SteeltoeOSS/MainSite/issues/54)
- [Shrinking the docs site window causes right navigation text to be cutoff](https://github.com/SteeltoeOSS/MainSite/issues/47)
> Responsive Layout

- articles/create-dotnet-microservice-projects-automatically-with-steeltoe-initializr.md
- articles/develop-dotNET-microservices-without-cloud-platform-lock-In.md
- articles/index.md
- articles/pivotal-contributes-steeltoe-to-the-net-foundation.md
- articles/steeltoe-application-configuration-with-spring-cloud-config.md
- articles/steeltoe-basics-in-7-minutes.md
- articles/steeltoe-modernize-net-apps-for-a-microservices-architecture.md
- articles/tech-tutorial-use-kubernetes-for-modern-net-apps-steeltoe-and-project-tye-are-your-path-to-productivity.md
- articles/writing-event-based-microservices-using-steeltoe.md
- metadata.json
- template/steeltoe/layout/_master.tmpl
- template/steeltoe/styles/main.css
- Add breadcrumbs to help differentiate pages (Documentation vs. API Browser vs Get Started)
- Fix blog landing page responsiveness
- Fix responsiveness for blog pages
> Breadcrumbs

- template/steeltoe/layout/_master.tmpl
- template/steeltoe/styles/main.css
- Reposition breadcrumbs for clarity
> Breadcrumb Redesign

- api/browser/v2/all/index.md
- template/steeltoe/partials/toc.tmpl.partial
Link version button tabs to v2 and v3 landing (index.html) pages.
> API Browser Version Buttons -> Landing Pages

- deploy/kubernetes/manifest.yaml
> Simplify k8s names

- guides/get-to-know-steeltoe/exercise1.md
- guides/get-to-know-steeltoe/exercise2.md
- guides/get-to-know-steeltoe/exercise3.md
- guides/get-to-know-steeltoe/exercise4.md
- guides/get-to-know-steeltoe/index.md
- guides/get-to-know-steeltoe/summary.md
- guides/index.md
- guides/security/jwt.md
- guides/security/redisstore.md
- guides/security/sso-oauth.md
- guides/security/sso-openid-netcore.md
- guides/service-connectors/mongo.md
- guides/service-connectors/mssql.md
- guides/service-connectors/mysql.md
- guides/service-connectors/oauth.md
- guides/service-connectors/postgresql.md
- guides/service-connectors/rabbitmq.md
- guides/service-connectors/redis.md
> Remove TOC Version Toggles in Guides

- api/v3/bootstrap/index.md
- api/v3/connectors/index.md
- api/v3/security/index.md
- api/v3/toc.yml
Address #159 
Also lightly improves a couple pages that are referenced by the new page
> document AddSteeltoe()

- api/v3/management/heapdump.md
Document the new heap dump setting added in https://github.com/SteeltoeOSS/Steeltoe/pull/659
> Include new HeapDumpType setting

- api/v3/stream/rabbit-binder.md
> Update binder reference with samples

- api/v3/stream/data-flow-stream.md
Remove TODOS in the doc and command and log output for SCDF on K8s
> Update documentation for SCDF on K8s

- articles/index.md
> Steeltoe Blog Broken Links

- api-filter.yml
- template/steeltoe/partials/toc.tmpl.partial
> Remove `RabbitMessageBuilder` from DocFx Build

- articles/index.md
- articles/releases/steeltoe-2-1-boosts-your-net-microservices-with-actuator-endpoints-distributed-tracing-and-deeper-support-for-the-frameworks-that-matter.md
- articles/releases/steeltoe-2-2-gives-your--microservices-a-boost.md
- articles/releases/steeltoe-2-4-boosts-dotnet-microservices-development.md
- articles/releases/steeltoe-3-0-packs-a-mighty-punch-with-many-new-features.md
- articles/releases/steeltoe-3-1-includes-event-driven-microservices-and-stream-based-data-Processing.md
- articles/releases/steeltoe-turns-2-0-adds-support-for-asp-net-core-2-0-credhub-and-a-sql-server-connector.md
- Make blog title stand out
- disable breadcrumbs
*Blog Release*
*Landing Page*
> Blog Release Title/Breadcrumbs

- template/steeltoe/partials/footer.tmpl.partial
- template/steeltoe/styles/main.css
Addresses MainSite Issue [#95](https://github.com/SteeltoeOSS/MainSite/issues/95)
> Fix Footer "Back To Top" Overlap

- template/steeltoe/partials/logo.tmpl.partial
Should resolve SteeltoeOSS/Documentation#210 in docs area
https://github.com/SteeltoeOSS/MainSite/pull/96
> Define logo image width

- template/steeltoe/layout/_master.tmpl
- template/steeltoe/partials/navbar.tmpl.partial
- template/steeltoe/styles/main.css
- template/steeltoe/styles/main1.js
Hide nav content when page is embedded, wider (and scaling) preview window
> Improved blog previews

- api/v3/management/springbootadmin.md
> Update SBA client docs for 3.1.0

- api/v3/management/using-endpoints.md
> Document configurable JsonSerializerOptions

- api/v3/discovery/netflix-eureka.md
> Eureka health & status paths can come from Management config

- api/v3/security/jwt-authentication.md
- api/v3/security/sso-oauth2.md
- api/v3/security/sso-open-id.md
> Document configurable auth httpclient timeouts

- guides/cloud-management/endpoints-framework.md
> Fix code listing for LoggingConfig

- api/v2/connectors/postgresql.md
- api/v3/connectors/postgresql.md
> Postgres Connectors uses Host, not Server #231

- api/v3/welcome/whats-new.md
- articles/index.md
- articles/releases/steeltoe-3-2-whats-new.md
- articles/whats-new-in-steeltoe-32.md
> Adds "what's new" for Steeltoe 3.2.0

- Production.env
> Define the Production environment

- api/v3/bootstrap/index.md
- api/v3/circuitbreaker/hystrix.md
- api/v3/configuration/cloud-foundry-provider.md
- api/v3/configuration/config-server-provider.md
- api/v3/configuration/kubernetes-providers.md
- api/v3/configuration/placeholder-provider.md
- api/v3/configuration/random-value-provider.md
- api/v3/discovery/initialize-discovery-client.md
- api/v3/logging/dynamic-logging-provider.md
- api/v3/logging/serilog-logger.md
- api/v3/management/metrics-endpoint.md
- api/v3/management/prometheus.md
- api/v3/management/springbootadmin.md
- api/v3/management/tasks.md
- api/v3/management/using-endpoints.md
- api/v3/security/credhub-api-client.md
- api/v3/security/jwt-authentication.md
- api/v3/security/mtls.md
- api/v3/security/redis-key-storage-provider.md
- api/v3/security/sso-oauth2.md
- api/v3/stream/rabbit-binder.md
- api/v3/stream/standalone-stream-rabbitmq.md
- api/v3/stream/stream-reference.md
- api/v3/tracing/index.md
- guides/cloud-management/distributed-tracing.md
> Update package references to Steeltoe 3.2.0

- api/v3/messaging/rabbitmq-intro.md
Clarify usage with WebAppBuilder
> Show Messaging usage with WebAppBuilder

- guides/stream/quick-start.md
> Update quick-start to include docs with webapplicationBuilder

- guides/service-discovery/eureka.md
Eureka server setup documentation updated as per WebAPI generated from Steeltoe Initializr.
> Eureka server setup documentation updated

- api/v3/management/using-endpoints.md
updated documentation to use the new and correct way to add auth required to an endpoint - issue #295
> added auth required to an actuator

- api/v4/discovery/hashicorp-consul.md
Hi everyone,
This PR is a supplement to the [Consul Discovery change supporting Metadata](https://github.com/SteeltoeOSS/Steeltoe/pull/1167/).
Please let me know if some stuff needs to be updated (like vocabulary or grammar), or if there are some other places that need to be updated.
Thanks!
> Consul - Update v4 docs about Metadata

- api/v3/discovery/hashicorp-consul.md
Hi everyone,
This PR updates v3 documentation for [this code change](https://github.com/SteeltoeOSS/Steeltoe/pull/1180)
Please let me know if some stuff needs to be updated (like vocabulary or grammar), or if there are some other places that need to be updated.
Thanks!
> Consul - Update v3 docs about Metadata

- api/v3/configuration/config-server-provider.md
fixes #299
Needs to be brought forward to v4
> Document Config Server PollingInterval

- api/v4/management/springbootadmin.md
https://github.com/SteeltoeOSS/Dockerfiles/pull/38#discussion_r1867507375
> Run SpringBootAdmin on port 9099

- api/v4/management/health.md
> Document X-Use-Status-Code-From-Response HTTP header

- api/v3/connectors/usage.md
> Document support for Cloud Native Service bindings in 3.2

- api/v4/management/threaddump.md
Companion to https://github.com/SteeltoeOSS/Steeltoe/pull/1438
> Changes related to content negotiation updates

- .github/workflows/build-and-stage.yml
- api/v4/management/health.md
Companion to https://github.com/SteeltoeOSS/Steeltoe/pull/1451
> Changes for health groups, showcomponents and showdetails

- api/v3/connectors/usage.md
> Main to v4

- api/v2/configuration/config-server-provider.md
- api/v3/configuration/config-server-provider.md
Update Logging-related content for Config Server client
> v2/v3: Replace very old method of creating a LoggerFactory

- .github/workflows/build-and-stage.yml
- .github/workflows/stage-prod-swap.yml
- src/Steeltoe.io/Components/Pages/Doc.razor
- src/Steeltoe.io/Components/Pages/DynamicLogging/Redirects.razor
Also adds a couple more redirects and fixes #374 by checking if a slot exists before trying to create
> Simpler stage-prod slot swap

- docs/docs/v4/management/health.md
> Fix Enabled property on health to match schema

- docs/docs/v4/management/springbootadmin.md
- docs/docs/v4/security/redis-key-storage-provider.md
Updates documentation, based on changes from https://github.com/SteeltoeOSS/Steeltoe/pull/1508.
> Update documentation for Spring Boot Admin registration

- docs/docs/v4/connectors/cosmosdb.md
- docs/docs/v4/connectors/microsoft-sql-server.md
- docs/docs/v4/connectors/mongodb.md
- docs/docs/v4/connectors/mysql.md
- docs/docs/v4/connectors/postgresql.md
- docs/docs/v4/connectors/rabbitmq.md
- docs/docs/v4/connectors/redis.md
- docs/docs/v4/connectors/usage.md
This PR updates the connector docs to match Steeltoe changes at https://github.com/SteeltoeOSS/Steeltoe/pull/1528.
> Update Connector docs
